### ISSUE TITLE
Add css and styling

### ISSUE THREAD

**Issue by tulikavijay** [tulikavijay/weather-app#1]
The app looks dull. It only has the functionality.

**Comment by ghost** [comment]
I did an `npm i` and ran `npm run develop` and it gave me the following error.

```
These relative modules were not found:

* ./index.css in ./src/layouts/index.js
* ../layouts/index.css in ./src/components/LocalWeather.js
>
```

**Comment by tulikavijay** [comment]
The app is based on GatsbyJs. You can install `gatsby` and `gatsby-cli`, then run `gatsby develop` on it
